services:
  php:
    container_name: sensor-page-php
    build: docker/php
    volumes:
      - ./src:/var/www/sensor-page

  nginx:
    build: docker/nginx
    container_name: sensor-page-nginx
    volumes:
      - ./src:/var/www/html
    ports:
      - 3267:80